/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Image;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import jankenponclient.Client;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author INSECT
 */
public class Game extends javax.swing.JFrame {

    //framedeki komponentlere erişim için satatik oyun değişkeni
    public static Game ThisGame;
    //ekrandaki resim değişimi için timer yerine thread
    public Thread tmr_slider;
    //karşı tarafın seçimi seçim -1 deyse seçilmemiş
    public int RivalSelection = -1;
    //benim seçimim seçim -1 deyse seçilmemiş
    public int myselection = -1;
    //icon dizileri
    public DefaultListModel dlmEkran;
    public DefaultListModel dlmOdaList;
    public DefaultListModel dlmUye;
    public ArrayList<String> OzelMesajListesi = new ArrayList<String>();
    public ArrayList<SohbetOdasi> odalar;
    public String kullaniciAdi;
    

    public HashMap<String, KisiselSohbet> SohbetMap = new HashMap<String, KisiselSohbet>();

    Random rand;

    /**
     * Creates new form Game
     */
    @SuppressWarnings("empty-statement")
    public Game() {
        initComponents();
        ThisGame = this;
        rand = new Random();
        dlmEkran = new DefaultListModel();
        jList_ekran.setModel(dlmEkran);
        odalar = new ArrayList<>();
        dlmUye = new DefaultListModel();
        jList_Users.setModel(dlmUye);
        dlmOdaList = new DefaultListModel();
        // resimleri döndürmek için tread aynı zamanda oyun bitiminide takip ediyor
        tmr_slider = new Thread(() -> {
            //soket bağlıysa dönsün
            while (Client.socket.isConnected()) {
                try {
                    //
                    Thread.sleep(100);
                    //eğer ikisinden biri -1 ise resim dönmeye devam etsin sonucu göstermesin
                    if (RivalSelection == -1 || myselection == -1) {
                        int g = rand.nextInt(2);

                    }// eğer iki seçim yapılmışsa sonuç gösterilebilir.  
                    else {

                        //sonuç el olarak gösterildikten 4 saniye sonra smiley gelsin
                        Thread.sleep(4000);
                        //smiley sonuç resimleri

                        tmr_slider.stop();

                        //7 saniye sonra oyun bitsin tekrar bağlansın
                        Thread.sleep(7000);
                        //Reset();

                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_gamer1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_connect = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_send_message = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_ekran = new javax.swing.JList();
        txtgmesaj = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Users = new javax.swing.JList();
        jButtonOzelSohbet = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        odaList = new javax.swing.JList();
        odaAdiTxt = new javax.swing.JTextField();
        katilButton = new javax.swing.JButton();
        odaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 570));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_gamer1.setBackground(new java.awt.Color(255, 153, 153));
        pnl_gamer1.setForeground(new java.awt.Color(51, 255, 0));
        pnl_gamer1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnl_gamer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 259));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Giriş Ekranı"));

        btn_connect.setBackground(new java.awt.Color(18, 30, 49));
        btn_connect.setText("Baglan");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });

        txt_name.setText("Name");
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(18, 30, 49));
        jLabel1.setText("Kullanıcı Adı");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_connect)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 80));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grup Sohbeti"));

        btn_send_message.setText("Toplu Mesaji Gönder");
        btn_send_message.setEnabled(false);
        btn_send_message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_send_messageActionPerformed(evt);
            }
        });

        jList_ekran.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(jList_ekran);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_send_message, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgmesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txtgmesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_send_message)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 300, 410));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Çevrimiçi Kullanıcılar"));

        jScrollPane2.setViewportView(jList_Users);

        jButtonOzelSohbet.setText("Özel Sohbet");
        jButtonOzelSohbet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOzelSohbetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOzelSohbet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonOzelSohbet)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 160, 410));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Grup Sohbeti"));
        jPanel3.setForeground(new java.awt.Color(102, 0, 0));

        odaList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(odaList);

        odaAdiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odaAdiTxtActionPerformed(evt);
            }
        });

        katilButton.setText("Odaya Katıl");
        katilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katilButtonActionPerformed(evt);
            }
        });

        odaButton.setText("Oda Oluştur");
        odaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(katilButton)
                        .addGap(22, 22, 22)
                        .addComponent(odaButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(odaAdiTxt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(odaAdiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(katilButton)
                    .addComponent(odaButton))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 230, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void reciveText(String msg) {
        dlmEkran.addElement(msg);
        jList_ekran.setModel(dlmEkran);
    }

    public void getNewUser(DefaultListModel msg) {

        jList_Users.setModel(msg);

    }

    public void OzelMesajiAl(OzelMesaj gelenMesaj) {

        String gonderen = gelenMesaj.gonderen;
        String ileti = gelenMesaj.mesaj;
        if (OzelMesajListesi.contains(gonderen)) {

            SohbetMap.get(gonderen).DlmOzelSohbetMesajlari.addElement(ileti);

            SohbetMap.get(gonderen).jListKisiselMesaj.setModel(SohbetMap.get(gonderen).DlmOzelSohbetMesajlari);

        } else {

            KisiselSohbet yeniSohbet = new KisiselSohbet();
            yeniSohbet.Kullanici = txt_name.getText();
            yeniSohbet.hedefKullanici = gonderen;

            yeniSohbet.DlmOzelSohbetMesajlari.addElement(ileti);
            yeniSohbet.jLabelKullanici.setText(txt_name.getText());
            yeniSohbet.jLabelHedef.setText(gonderen);
            yeniSohbet.jListKisiselMesaj.setModel(yeniSohbet.DlmOzelSohbetMesajlari);
            yeniSohbet.setVisible(true);

            SohbetMap.put(gonderen, yeniSohbet);

            OzelMesajListesi.add(gonderen);

        }

    }


    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        this.kullaniciAdi = txt_name.getText();
        //bağlanılacak server ve portu veriyoruz
        //Client.Start("127.0.0.1", 2000);
        Client.Start("18.117.86.253", 2000);
        
        //başlangıç durumları

        btn_connect.setEnabled(false);
        txt_name.setEnabled(false);
        btn_send_message.setEnabled(true);


    }//GEN-LAST:event_btn_connectActionPerformed

    private void btn_send_messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_send_messageActionPerformed

        String name = txt_name.getText();

        //metin mesajı gönder
        Message msg = new Message(Message.Message_Type.Text);
        String x = txtgmesaj.getText();
        msg.content = name + " :" + txtgmesaj.getText();
        Client.Send(msg);
        txtgmesaj.setText("");


    }//GEN-LAST:event_btn_send_messageActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //form kapanırken clienti durdur
        Client.Stop();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonOzelSohbetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOzelSohbetActionPerformed

        if (!OzelMesajListesi.contains((String) jList_Users.getSelectedValue())) {

            KisiselSohbet OzelSohbet = new KisiselSohbet();
            OzelSohbet.DlmOzelSohbetMesajlari = new DefaultListModel();
            OzelSohbet.Kullanici = txt_name.getText();
            OzelSohbet.hedefKullanici = (String) jList_Users.getSelectedValue();
            OzelSohbet.jLabelKullanici.setText(txt_name.getText());
            OzelSohbet.jLabelHedef.setText((String) jList_Users.getSelectedValue());

            OzelMesajListesi.add(((String) jList_Users.getSelectedValue()));

            SohbetMap.put((String) jList_Users.getSelectedValue(), OzelSohbet);

            OzelSohbet.setVisible(true);

        }

    }//GEN-LAST:event_jButtonOzelSohbetActionPerformed

    public void getOdalar(ArrayList<String> odalar){
        dlmOdaList.removeAllElements();
        odaList.removeAll();
        for (String oda : odalar) {
            dlmOdaList.addElement(oda);
        }
        odaList.setModel(dlmOdaList);
    }
    
    private void odaAdiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odaAdiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odaAdiTxtActionPerformed

    private void odaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odaButtonActionPerformed
        SohbetOdasi so = new SohbetOdasi(this.kullaniciAdi, odaAdiTxt.getText());
        odalar.add(so);
        so.kullaniciList.add(this.kullaniciAdi);
        so.setVisible(true);
        Message msg = new Message(Message.Message_Type.OdaOlustur);
        msg.content = so.odaAdi;
        Client.Send(msg);
        
    }//GEN-LAST:event_odaButtonActionPerformed
    
    public SohbetOdasi odaBul(String odaİsmi){
        
        for (SohbetOdasi arananOda : this.odalar) {
           if(arananOda.odaAdi.equalsIgnoreCase(odaİsmi)){
               System.out.println("OdaBulundu");
               return arananOda;
           }
        }
        
        return null;
    }
    
    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void katilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katilButtonActionPerformed
        SohbetOdasi so = new SohbetOdasi(this.kullaniciAdi, (String) odaList.getSelectedValue());
        this.odalar.add(so);
        so.kullaniciList.add(this.kullaniciAdi);
        so.setVisible(true);
        Message msg = new Message(Message.Message_Type.OdayaKatil);
        msg.content = odaList.getSelectedValue();
        System.out.println("Mesaj Clienttan yollanıyor");
        Client.Send(msg);
        System.out.println("Yollandı");
    }//GEN-LAST:event_katilButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_connect;
    public javax.swing.JButton btn_send_message;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonOzelSohbet;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JList jList_Users;
    public static javax.swing.JList jList_ekran;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton katilButton;
    private javax.swing.JTextField odaAdiTxt;
    private javax.swing.JButton odaButton;
    private javax.swing.JList odaList;
    private javax.swing.JPanel pnl_gamer1;
    public javax.swing.JTextField txt_name;
    private javax.swing.JTextField txtgmesaj;
    // End of variables declaration//GEN-END:variables
}
