/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import javax.swing.DefaultListModel;
import jankenponclient.Client;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Fatih
 */
public class KisiselSohbet extends javax.swing.JFrame {

    public DefaultListModel DlmOzelSohbetMesajlari = new DefaultListModel();

    public String Kullanici;
    public String hedefKullanici;

    /**
     * Creates new form KisiselSohbet
     */
    public KisiselSohbet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelHedef = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelKullanici = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListKisiselMesaj = new javax.swing.JList();
        jTextFieldKisiselMesaj = new javax.swing.JTextField();
        jButtonKisiselGonder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 570));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kişisel Sohbet"));

        jLabel2.setText("Sohbet Ekranı");

        jLabelHedef.setText("jLabel2");

        jLabel1.setText("İle");

        jLabelKullanici.setText("jLabel1");

        jScrollPane1.setViewportView(jListKisiselMesaj);

        jButtonKisiselGonder.setText("Mesaj Gonder");
        jButtonKisiselGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKisiselGonderActionPerformed(evt);
            }
        });

        jButton1.setText("Dosya Gonder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelKullanici)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelHedef)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jTextFieldKisiselMesaj, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jButtonKisiselGonder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKullanici)
                    .addComponent(jLabel1)
                    .addComponent(jLabelHedef)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldKisiselMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonKisiselGonder)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKisiselGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKisiselGonderActionPerformed

        Message msg = new Message(Message.Message_Type.OzelMesaj);
        String x = jTextFieldKisiselMesaj.getText();
        msg.content = new OzelMesaj(Kullanici, hedefKullanici, Kullanici + " :" + jTextFieldKisiselMesaj.getText());

        Client.Send(msg);

        DlmOzelSohbetMesajlari.addElement(Kullanici + " :" + jTextFieldKisiselMesaj.getText());
        jTextFieldKisiselMesaj.setText("");

        jListKisiselMesaj.setModel(DlmOzelSohbetMesajlari);
    }//GEN-LAST:event_jButtonKisiselGonderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fs = new JFileChooser();
        fs.setDialogTitle("Dosya Sec");
        int result = fs.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File fi = fs.getSelectedFile();
            byte[] bufferdizi = new byte[(int) fi.length()]; // byte olarak içine atar.
            FileInputStream fis;
            try {
                fis = new FileInputStream(fi);
                BufferedInputStream bis = new BufferedInputStream(fis);

                bis.read(bufferdizi, 0, bufferdizi.length);
                Message msg = new Message(Message.Message_Type.DosyaGonder);
                msg.content = new OzelMesaj(Kullanici, hedefKullanici, bufferdizi, fi.getName());
                Client.Send(msg);

                Message msg1 = new Message(Message.Message_Type.OzelMesaj);
                msg1.content = new OzelMesaj(Kullanici, hedefKullanici, Kullanici + " :" + fi.getName() + " isimli dosya paylaşıldı");

                Client.Send(msg1);
                DlmOzelSohbetMesajlari.addElement(Kullanici + " :" + fi.getName() + " isimli dosya paylaşıldı");
              

                jListKisiselMesaj.setModel(DlmOzelSohbetMesajlari);

                System.out.println(((OzelMesaj) msg.content).dosyaAdi + " Gonderildi");

            } catch (IOException ex) {
                Logger.getLogger(KisiselSohbet.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KisiselSohbet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonKisiselGonder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabelHedef;
    public static javax.swing.JLabel jLabelKullanici;
    public static javax.swing.JList jListKisiselMesaj;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldKisiselMesaj;
    // End of variables declaration//GEN-END:variables
}
