/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import javax.swing.DefaultListModel;
import jankenponclient.Client;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Fatih
 */
public class KisiselSohbet extends javax.swing.JFrame {

    public DefaultListModel DlmOzelSohbetMesajlari = new DefaultListModel();

    public String Kullanici;
    public String hedefKullanici;

    /**
     * Creates new form KisiselSohbet
     */
    public KisiselSohbet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGeri = new javax.swing.JButton();
        jTextFieldKisiselMesaj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListKisiselMesaj = new javax.swing.JList();
        jButtonKisiselGonder = new javax.swing.JButton();
        jLabelKullanici = new javax.swing.JLabel();
        jLabelHedef = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonGeri.setText("jButton2");

        jTextFieldKisiselMesaj.setText("jTextField1");

        jListKisiselMesaj.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListKisiselMesaj);

        jButtonKisiselGonder.setText("jButton1");
        jButtonKisiselGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKisiselGonderActionPerformed(evt);
            }
        });

        jLabelKullanici.setText("jLabel1");

        jLabelHedef.setText("jLabel2");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelKullanici)
                        .addGap(64, 64, 64)
                        .addComponent(jLabelHedef))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldKisiselMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonGeri)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonKisiselGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKullanici)
                    .addComponent(jLabelHedef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldKisiselMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKisiselGonder)
                    .addComponent(jButtonGeri))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKisiselGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKisiselGonderActionPerformed

        Message msg = new Message(Message.Message_Type.OzelMesaj);
        String x = jTextFieldKisiselMesaj.getText();
        msg.content = new OzelMesaj(Kullanici, hedefKullanici, Kullanici + " :" + jTextFieldKisiselMesaj.getText());

        Client.Send(msg);

        DlmOzelSohbetMesajlari.addElement(Kullanici + " :" + jTextFieldKisiselMesaj.getText());
        jTextFieldKisiselMesaj.setText("");

        jListKisiselMesaj.setModel(DlmOzelSohbetMesajlari);
    }//GEN-LAST:event_jButtonKisiselGonderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fs = new JFileChooser();
        fs.setDialogTitle("Dosya Sec");
        int result = fs.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File fi = fs.getSelectedFile();
            byte[] bufferdizi = new byte[(int) fi.length()]; // byte olarak içine atar.
            FileInputStream fis;
            try {
                fis = new FileInputStream(fi);
                BufferedInputStream bis = new BufferedInputStream(fis);

                bis.read(bufferdizi, 0, bufferdizi.length);
                Message msg = new Message(Message.Message_Type.DosyaGonder);
                msg.content = new OzelMesaj(Kullanici, hedefKullanici, bufferdizi, fi.getName());
                Client.Send(msg);

                Message msg1 = new Message(Message.Message_Type.OzelMesaj);
                msg1.content = new OzelMesaj(Kullanici, hedefKullanici, Kullanici + " :" + fi.getName() + " isimli dosya paylaşıldı");

                Client.Send(msg1);
                DlmOzelSohbetMesajlari.addElement(Kullanici + " :" + fi.getName() + " isimli dosya paylaşıldı");
              

                jListKisiselMesaj.setModel(DlmOzelSohbetMesajlari);

                System.out.println(((OzelMesaj) msg.content).dosyaAdi + " Gonderildi");

            } catch (IOException ex) {
                Logger.getLogger(KisiselSohbet.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KisiselSohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KisiselSohbet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGeri;
    private javax.swing.JButton jButtonKisiselGonder;
    public static javax.swing.JLabel jLabelHedef;
    public static javax.swing.JLabel jLabelKullanici;
    public static javax.swing.JList jListKisiselMesaj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldKisiselMesaj;
    // End of variables declaration//GEN-END:variables
}
